version: "3.7"
services:
  web:
    image: jobcafe-api:latest
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    networks:
      - net
    volumes:
      - ".:/src"
      - "./gradle-cache:/home/gradle/.gradle"
    depends_on:
      - db
  db:
    image: mariadb:10.4.7
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      MYSQL_USER: alex
      MYSQL_PASSWORD: alex
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobcafe
    networks:
      - net
networks:
  net:
